version: '3.8'

services:
  local-mysql:
    image: mysql:8.2.0
    container_name: local-mysql
    environment:
      # Don't do this. This is just an example.
      MYSQL_ROOT_PASSWORD: 12345
    networks:
      - wordpress-network

  local-wordpress:
    image: wordpress
    container_name: local-wordpress
    ports:
      - "8080:80"
    networks:
      - wordpress-network
    depends_on:
      - local-mysql
    environment:
      WORDPRESS_DB_HOST: local-mysql
      WORDPRESS_DB_USER: root
      # Don't do this. This is just an example.
      WORDPRESS_DB_PASSWORD: 12345
      WORDPRESS_DB_NAME: wordpress

networks:
  wordpress-network:
    driver: bridge
